### ISSUE TITLE
Set up classification pipeline for lab change prediction

### ISSUE THREAD

**Issue by raikens1** [HealthRex/CDSS#115]
# Classification Problem
Given a definition of "change" for a lab test result, construct change/no-change labels of each observation and train a classifier.

## ToDo
- [x] propose some definitions for "change" - possibly try a bunch (#130)
- [x] write code to generate labels for a "change" function (#132)
- [ ] make a script like LabNormalityPredictionPipeline.py for this task

**Comment by raikens1** [comment]
Probably want to write something like LabNormalityPredictionPipeline.py for this.

**Comment by raikens1** [comment]
Initial Set-up done!  Closing!  For more, see #135
