### ISSUE TITLE
Run LabChangePrediction.py for different definitions of "change," or lab test types:

### ISSUE THREAD

**Issue by raikens1** [HealthRex/CDSS#140]
To Do:
- [x] decide which "change" definitions we want
- [x] decide which other lab types we want
- [x] make sure LabChangePredictionPipeline doesn't choke when we change the lab type #135 
- [x] Decide on fastest way to run LabChangePredictionPipeline for a bunch of tests #135 
- [x] Run a bunch of tests (see below)

# How to make this faster?
- [ ] better parallelize LabChangePrediction.py #135 
- [ ] optimize ec2 compute environment #156

**Comment by raikens1** [comment]
Currently have:
- LABCK; percent; 0.5 - best AUROC 0.7896 (Random Forest)
- LABCK; percent; 0.25  - (Running now)

**Comment by raikens1** [comment]
**Goal:** Run ~20 of the top non-panel tests by volume with ~12000 episodes at 50, 40, 30, 20, and 10% change.

# To Do
-   "LABBLC", "LABBLC2", "LABCAI", "LABURNC", "LABLACWB",
    "LABA1C", "LABHEPAR", "LABCDTPCR", "LABPCTNI", "LABPLTS",
    "LABLAC", "LABLIPS", "LABRESP", "LABTSH", "LABHCTX",

# In Progress
- LABMGN, LABPHOS, LABPTT, LABTNI

# Done
- LABCK, LABPT
