### ISSUE TITLE
Updates to Sim UI and Tracker

### ISSUE THREAD

**Issue by mrlsdvd** [HealthRex/CDSS#237]
**Important**

Sim UI:
- [x] Add 'refresh recommender' functionality (graph icon next to 'New Orders')
- [x] Implement toggling of recommended link when recommender enabled/not-enabled

- [x] Add blocking functionality that prevents user from moving time forward before signing orders

Tracker:
- [x] Make sure that common and related order lists can be separated

Sim Data:
- [x] Change default value of Sodium from 146 to 141
- [x] Create default result for abdominal ultrasound ["No intra-abdominal abnormalities noted"]
- [x] Add FFP Fresh Frozen Plasma Product from blood bank to trigger for hematemesis (similar to other nursing FFP) **[From Jonathan Chiang]**
- [x] Some extra rare Transfuse FFP and Transfuse RBC orders, but sometimes this is what people pick when they are searching for options. Need to add those as valid state transition triggers.
- [x] Change GI consult note to include 'please consult again after stabilization'
- [x] Fix GI Bleed case
- [x] Make respiratory virus (DFA) panel have same results as PCR panel
- [x] Make Neutropenic Fever (anion gap)  elevated to 16
- [x ] Change default Chloride level to 106
- [x] Neutropenic fever chloride level should be such that Na - Cl - CO2 = Anion Gap
      So if Na = 141, CO2 = 19, Anion Gap =16, then Cl = 106
- [x] Add ultrasound to description of US items
- [x] Add DCCV abbreviation to description of cardioversion
- [x] Add TTE abbreviation to description of echocardiogram

*Good to have*
- [ ] *Remove duplicate items between common and related order lists*
- [ ] Make sure that all end states have final 'done' note

- [ ] Implement unittest to make sure that metrics can be extracted correctly
- [ ] Modify tracker to start timer when focus changes to tab
- [ ] Figure out how to save JSON data file without explicit button click (automatically?)

 - [ ] Move the stride.clinical_item.ClinicalItemDataLoader.add_clinical_item_synonyms functions to the same extraClinicalItems.sql script. Look for anywhere it's being used or referenced anywhere and redirect them to be here instead.

**Comment by JonathanChiang** [comment]
![Screen Shot 2019-05-07 at 4 33 51 PM](https://user-images.githubusercontent.com/13003102/57388013-3f110f00-716c-11e9-96f1-b5b2c6d8a3c1.png)

**Comment by JonathanChiang** [comment]
The case above identifies two of the issues. Somehow this case triggered death for the patient and also includes the stomach abdomen. I'm guessing that the FFP trigger for the sim state didn't apply.

**Comment by JonathanChiang** [comment]
- **Things to Review** 
- [ ] sim_state triggers on ordering everything at once (multiple notes for hematemesis) 
- [ ] headache case: is there clinical result for lumbar puncture 
- [ ] is there a blood culture result for fever b 
- [ ] is there a result for d-dimer

**Comment by JonathanChiang** [comment]
Deescalating priority since David covered major issues: the remaining tasks are QOL improvements which would be nice to have, but don't necessarily impact the clinical decision-making process and may potentially bias past results.

**Comment by jonc101** [comment]
Not actively developing or using mock UI anymore
